version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certs:/etc/nginx/certs
    depends_on:
      - php
      - mysql
    networks:
      reseau_net:
        ipv4_address: 172.28.1.1
  mysql:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdata
    ports:
      - "3333:3306"
    networks:
      reseau_net:
        ipv4_address: 172.28.1.2
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
      - "6001:6001"
    networks:
      reseau_net:
        ipv4_address: 172.28.1.3
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - UPLOAD_LIMIT=1G
      - PMA_ARBITRARY=1
    networks:
      reseau_net:
        ipv4_address: 172.28.1.4
networks:
  reseau_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  dbvol:
